### PR TITLE
Fixes exceotion handling

### PR DESCRIPTION
**Pull request by freemo**

### CODE REVIEW

**Comment by patham9** [comment]
I hope I can review them next weekend step by step, too much changes to core to be able to approve them now.

**Comment by PtrMan** [comment]
See - you managed to cap out patrick.
This is frustrating for me too

**Comment by patham9** [comment]
Oops wanted to write next week not weekend, as today and tomorrow I need to prepare for the final.
But maybe I can do it today let's see.

**Comment by patham9** [comment]
This doesn't build for me so I can not approve it. See my attached stack trace: https://gist.github.com/patham9/519242493e6e44a69be3abbcae3d0e14
I tried a lot to resolve it but failed doing so. I hope we can find more reliable build configurations in the future, meaning reliable as the one we had before without loosing Maven benefits would be ideal.

**Pull request merged**
