### PR TITLE
Refactor: CompositionalRules.introVarOuter()

### PR DESCRIPTION
**Pull request by PtrMan**

### CODE REVIEW

**Comment by PtrMan** [comment]
@patham9 The static method names could be better, any suggestions?

**Comment by patham9** [comment]
Ehm small mistake from my side: it's whether it is also an ExtSet or also an IntSet

Change the names of "enableSpecialCase" to "firstIsImage" and "enableRetCommonTerm" to "secondIsSameImage".

**Comment by freemo** [comment]
@patham9 again method overloading makes more sense here. The only
difference between the methods are the parameters and your choice of method
name highlights this. So It is a typical case for method overloading.

**Comment by patham9** [comment]
@freemo: Both methods do something different, and the naming I suggested captures that.

**Comment by freemo** [comment]
@patham9 overloaded methods always do something different. IF they didnt
you woudnt need seperate methods in the first place. Do they return similar
values with similar meanings?

**Comment by patham9** [comment]
@freemo: The parameters are the same here in fact, so how could overloading apply here?

**Comment by freemo** [comment]
@patham9 ahh missed that, your correct then

**Pull request merged**
