### PR TITLE
better NLP with "connectors"(and)

### PR DESCRIPTION
**Pull request by PtrMan**
NLP terrorism has begun

### CODE REVIEW

**Comment by patham9** [comment]
Looks nearly fine: Why do you use | instead of &&?
Fix it and I will look again and potentially close the pull request.

Best regards,
Patrick

**Comment by patham9** [comment]
Looks nearly fine: But why do you use | instead of &&?
Fix it and I will look again and potentially close the pull request.

Best regards,
Patrick

**Comment by PtrMan** [comment]
I confused the semantics. I fixed it as you suggested.

**Comment by patham9** [comment]
Fine for now, but we will soon have the (non-temporal) sequential conjunction connector which will make NLP knowledge even easier to be represented.

**Pull request merged**
