### PR TITLE
Add: TestSystemOperator to test the ^system op

### PR DESCRIPTION
**Pull request by PtrMan**
Tests if the call to the ^system op are done correctly.
Is not testing if the result is ok.

Test with the bash script moved into the root directory of the process. It is now in opennars-parent

>#!/bin/bash
>
>echo "true"
>exit 0 # success

### CODE REVIEW

**Comment by TonyLo1** [comment]
As we discussed earlier, there are some outstanding issues with the implementation. These are listed here for the record:
1. How to handle a hung system process - timeout?
2. How to handle return values that require parsing to terms?
3. How to specify the directory where the system call is executed?
4. How to handle error code and return value?

**Comment by PtrMan** [comment]
I would suggest that it doesn't parse to terms, maybe we need a string term type so anything can be enclosed with "" or '' and ' itself can be escaped with \' (same for " as \").

**Comment by TonyLo1** [comment]
GMPOW2, for some reason I can't see your email comment here regarding not parsing the return string. I agree that in the short term this will be ok as the use cases we have planned don't require  statements to be returned. However, future use cases may require statements to be returned and this would require parsing the return string. For example 

(^system, (SELF}, func $1, ?1) 

where ?1 should bind to <a --> b> 

I can see this being a common requirement which is not currently supported.

**Comment by TonyLo1** [comment]
Can you address the issues raised by the Codacy quality review please :)

**Comment by TonyLo1** [comment]
Can you add some test cases that show vars being unified before the system call ?

Something like: (^system, (SELF}, func {$1}, #1)

and provide a statement that can unify with the operator var

I realise this is outside the scope of the ^system operator call but it would be helpful to show it being able to handle vars and unification in one place.

**Comment by patham9** [comment]
It should be able to without a problem.
A test is always good though, to avoid surprises. :)

Am Mo., 7. Okt. 2019 um 19:05 Uhr schrieb Tony Lofthouse <
notifications@github.com>:

**Comment by TonyLo1** [comment]
In a break with convention I will merge the PR as it is needed urgently.

**Pull request merged**
