### PR TITLE
Overridable Parameters

### PR DESCRIPTION
**Pull request by PtrMan**

### CODE REVIEW

**Comment by PtrMan** [comment]
SOC - separation of concerns https://en.wikipedia.org/wiki/Separation_of_concerns

**Comment by PtrMan** [comment]
Is the concern of Nar to take utility and other BS methods now?

**Comment by PtrMan** [comment]
It's not the concern of Nar to set parameters

**Comment by patham9** [comment]
I see your point. but why the constructor mess when all is necessary to apply that method to the params of an existing Nar?

**Comment by PtrMan** [comment]
Because one main use is to set the # of concepts

**Comment by PtrMan** [comment]
Is this fine now?

**Comment by PtrMan** [comment]
I pulled it into Nar

**Pull request merged**
