### PR TITLE
Generalized Intersection into one class

### PR DESCRIPTION
**Pull request by PtrMan**

### CODE REVIEW

**Comment by PtrMan** [comment]
The reason for this particular refactoring are some redundancies in the deriver which can be simplified with this.

**Comment by PtrMan** [comment]
This can be hidden in a member.

It is a simplification in my opinion because we can generalize some deriver copy and pasted code (where it is used).

**Comment by PtrMan** [comment]
I made an error somewhere - will soon take a look at it.

**Comment by patham9** [comment]
so far it's not a simplifaction but a complification that leads to duplicated code all over the place.

**Comment by PtrMan** [comment]
Closed because not that important

**Pull request closed without merging**
